#!/bin/bash
while true; do
read LINE
echo "$LINE" > pipe
case "$LINE" in
	"+") ;;
	"*") ;;
	[0-9]*) ;;
  	"QUIT")
		echo "exit"
		killall tail
		exit
		;;
	*)
		echo "ERROR"
		killall tail
		exit
		;;
esac
done
